// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/WhiteRoseLK/genesis/internal/testutil"
)

// TestModulesScaffoldGeneratesBuildableModule is the M3 acceptance criterion
// (doc 08): a module generated by scaffold compiles — seen from the CLI
// command rather than the internal/scaffold package directly
// (internal/scaffold/scaffold_test.go already covers discovery/Describe).
func TestModulesScaffoldGeneratesBuildableModule(t *testing.T) {
	root := testutil.SandboxRepo(t)
	name := "cliscaffoldtest"
	dir := filepath.Join(root, "modules", name)

	origWD, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(root); err != nil {
		t.Fatal(err)
	}
	defer func() { _ = os.Chdir(origWD) }()

	out, err := runCLI(t, "modules", "scaffold", name, "--provides", "test.scaffold/v1")
	if err != nil {
		t.Fatalf("modules scaffold: %v\n%s", err, out)
	}
	if !strings.Contains(out, name) {
		t.Errorf("scaffold output = %q, want the module name mentioned", out)
	}
	if _, err := os.Stat(filepath.Join(dir, "module.yaml")); err != nil {
		t.Errorf("module.yaml absent: %v", err)
	}
}
