// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/WhiteRoseLK/genesis/internal/modulehost"
	"github.com/WhiteRoseLK/genesis/internal/testutil"
)

// TestScaffoldInstallDiscoverDescribe is the M3 acceptance criterion as a
// whole (doc 08): "a module generated by scaffold compiles, is discovered and
// answers Describe" — chained end to end (scaffold -> install -> Discover ->
// Launch -> Describe over real gRPC), rather than checked by separate tests
// that each cover a single link.
func TestScaffoldInstallDiscoverDescribe(t *testing.T) {
	root := testutil.SandboxRepo(t)
	name := "e2escaffoldtest"
	sourceDir := filepath.Join(root, "modules", name)

	origWD, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(root); err != nil {
		t.Fatal(err)
	}
	defer func() { _ = os.Chdir(origWD) }()

	if _, err := runCLI(t, "modules", "scaffold", name, "--provides", "test.e2e/v1"); err != nil {
		t.Fatalf("modules scaffold: %v", err)
	}

	useTempHomeKeepingGoCache(t)
	lockFile := filepath.Join(t.TempDir(), "genesis.lock")
	if out, err := runCLI(t, "modules", "install", sourceDir, "--lock-file", lockFile); err != nil {
		t.Fatalf("modules install: %v\n%s", err, out)
	}

	// Discovery: the installed module must appear under the standard search
	// directories (docs/02-architecture.md).
	found, err := modulehost.Discover(modulehost.SearchPaths())
	if err != nil {
		t.Fatalf("Discover: %v", err)
	}
	var installed *modulehost.Installed
	for i := range found {
		if found[i].Name == name {
			installed = &found[i]
		}
	}
	if installed == nil {
		t.Fatalf("module %q not discovered among %+v", name, found)
	}

	// Describe through the real gRPC/go-plugin protocol, not a direct Go call.
	client, err := modulehost.Launch(installed.BinaryPath, installed.Manifest)
	if err != nil {
		t.Fatalf("Launch: %v", err)
	}
	defer client.Close()

	manifest, err := client.Describe(context.Background())
	if err != nil {
		t.Fatalf("Describe: %v", err)
	}
	if manifest.GetName() != name {
		t.Errorf("Describe().Name = %q, want %q", manifest.GetName(), name)
	}
	if len(manifest.GetProvides()) != 1 || manifest.GetProvides()[0].GetFunction() != "test.e2e/v1" {
		t.Errorf("Describe().Provides = %+v, want [test.e2e/v1]", manifest.GetProvides())
	}
}
