// SPDX-License-Identifier: Apache-2.0

package scaffold

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/WhiteRoseLK/genesis/internal/testutil"
)

// TestGenerateProducesBuildableConformingModule is the M3 acceptance criterion
// (doc 08): a module generated by scaffold compiles and passes its own
// conformance suite. It is generated in a temporary repository, never in the
// real one (testutil.SandboxRepo).
func TestGenerateProducesBuildableConformingModule(t *testing.T) {
	root := testutil.SandboxRepo(t)
	name := "scaffoldtest"
	dir := filepath.Join(root, "modules", name)

	got, err := Generate(root, name, []string{"dns.zone/v1", "dns.resolver/v1"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if got != dir {
		t.Fatalf("Generate returned %q, want %q", got, dir)
	}

	for _, f := range []string{"go.mod", "module.yaml", "main.go", "schema.json", "conformance_test.go"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err != nil {
			t.Errorf("expected file missing: %s: %v", f, err)
		}
	}

	build := exec.Command("go", "build", "./...")
	build.Dir = dir
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("go build on the generated module: %v\n%s", err, out)
	}

	conformance := exec.Command("go", "test", "./...", "-run", "Conformance", "-v")
	conformance.Dir = dir
	if out, err := conformance.CombinedOutput(); err != nil {
		t.Fatalf("conformance suite on the generated module: %v\n%s", err, out)
	}
}
