// SPDX-License-Identifier: Apache-2.0

//go:build docker

package integration

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"testing"

	"github.com/WhiteRoseLK/genesis/internal/broker"
	"github.com/WhiteRoseLK/genesis/internal/modulehost"
	"github.com/WhiteRoseLK/genesis/internal/runner"
	"github.com/WhiteRoseLK/genesis/internal/secrets"
	"github.com/WhiteRoseLK/genesis/internal/testutil"
	pkiissuerv1 "github.com/WhiteRoseLK/genesis/sdk/go/gen/functions/pki/issuer/v1"
	modulev1 "github.com/WhiteRoseLK/genesis/sdk/go/gen/module/v1"
)

// launchStepCA launches step-ca with a broker session to core.container/v1
// (real Docker) and core.secrets/v1 (real, age+file) — the same mechanism as
// modules/coredns, reproduced here to test the module in isolation.
func launchStepCA(t *testing.T) pkiissuerv1.PkiIssuerClient {
	t.Helper()
	rt := testutil.RequireRuntime(t)
	return launchStepCAWithStore(t, rt, newTestSecretsStore(t))
}

// launchStepCAWithStore relaunches step-ca (a new process, like a restart of
// the core) on the SAME secret store, to prove the CA's idempotence across two
// separate runs.
func launchStepCAWithStore(t *testing.T, rt *runner.ContainerRuntime, store *secrets.FileStore) pkiissuerv1.PkiIssuerClient {
	t.Helper()
	ctx := context.Background()

	registry := broker.NewRegistry()
	registry.SetNative("core.container/v1", broker.NativeContainer(rt))
	registry.SetNative("core.secrets/v1", broker.NativeSecrets(store))

	binaryPath, manifest := buildModule(t, "step-ca")
	client, err := modulehost.Launch(binaryPath, manifest)
	if err != nil {
		t.Fatalf("Launch: %v", err)
	}
	t.Cleanup(client.Close)

	token := registry.OpenSession(client.Broker(), "step-ca", []string{"core.container/v1", "core.secrets/v1"})
	checkResp, err := client.Module().Check(ctx, &modulev1.StepRequest{RunId: "test", BrokerToken: token})
	if err != nil {
		t.Fatalf("Check: %v", err)
	}
	if checkResp.GetStatus() != modulev1.CheckResult_STATUS_TODO {
		t.Fatalf("Check().Status = %v, want TODO (not bootstrapped yet)", checkResp.GetStatus())
	}

	seedToken := registry.OpenSession(client.Broker(), "step-ca", []string{"core.container/v1", "core.secrets/v1"})
	seedResp, err := client.Module().SeedUp(ctx, &modulev1.StepRequest{RunId: "test", BrokerToken: seedToken})
	if err != nil {
		t.Fatalf("SeedUp: %v", err)
	}
	if seedResp.GetStatus() != modulev1.StepResult_STATUS_OK {
		t.Fatalf("SeedUp().Status = %v", seedResp.GetStatus())
	}

	conn, err := client.DispenseFunction("pki.issuer/v1")
	if err != nil {
		t.Fatalf("DispenseFunction(pki.issuer/v1): %v", err)
	}
	return pkiissuerv1.NewPkiIssuerClient(conn)
}

func parseCertPEM(t *testing.T, certPEM string) *x509.Certificate {
	t.Helper()
	block, _ := pem.Decode([]byte(certPEM))
	if block == nil {
		t.Fatalf("PEM illisible: %q", certPEM)
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		t.Fatalf("unreadable certificate: %v", err)
	}
	return cert
}

func verifyAgainstRoot(t *testing.T, chainPEM, rootPEM string) {
	t.Helper()
	roots := x509.NewCertPool()
	if !roots.AppendCertsFromPEM([]byte(rootPEM)) {
		t.Fatal("racine illisible")
	}
	intermediates := x509.NewCertPool()
	var leaf *x509.Certificate
	rest := []byte(chainPEM)
	for {
		var block *pem.Block
		block, rest = pem.Decode(rest)
		if block == nil {
			break
		}
		cert, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			t.Fatalf("unreadable certificate in the chain: %v", err)
		}
		if leaf == nil {
			leaf = cert
			continue
		}
		intermediates.AddCert(cert)
	}
	if leaf == nil {
		t.Fatal("no leaf certificate in the chain")
	}
	if _, err := leaf.Verify(x509.VerifyOptions{Roots: roots, Intermediates: intermediates, KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageAny}}); err != nil {
		t.Fatalf("chain invalid up to the root: %v", err)
	}
}

// TestStepCAIssuesAndSignsRealCertificates proves, against the real
// smallstep/step-ca container (docs/08-milestones.md, M7), that IssueCert and
// SignCSR produce certificates really valid up to the root generated by the
// CA, that CAChain exposes this root, and that SignSSH stays an explicit stub
// (no consumer yet).
func TestStepCAIssuesAndSignsRealCertificates(t *testing.T) {
	pki := launchStepCA(t)
	ctx := context.Background()

	chain, err := pki.CAChain(ctx, &pkiissuerv1.Empty{})
	if err != nil {
		t.Fatalf("CAChain: %v", err)
	}
	if chain.GetChainPem() == "" {
		t.Fatal("CAChain: empty chain")
	}
	rootCert := parseCertPEM(t, chain.GetChainPem())
	if !rootCert.IsCA {
		t.Error("CAChain: the last certificate of the chain is not a CA")
	}

	issued, err := pki.IssueCert(ctx, &pkiissuerv1.IssueCertRequest{
		CommonName: "infra01.lab.internal",
		Sans:       []string{"infra01.lab.internal"},
		TtlSeconds: 3600,
	})
	if err != nil {
		t.Fatalf("IssueCert: %v", err)
	}
	if issued.GetPrivateKeyPem() == "" {
		t.Error("IssueCert: empty private_key_pem, want a key generated by the provider")
	}
	leaf := parseCertPEM(t, issued.GetCertPem())
	if leaf.Subject.CommonName != "infra01.lab.internal" {
		t.Errorf("IssueCert: CN = %q, want infra01.lab.internal", leaf.Subject.CommonName)
	}
	verifyAgainstRoot(t, issued.GetChainPem(), chain.GetChainPem())

	// SignCSR: a real CSR generated here (the private key never leaves this
	// process, unlike IssueCert).
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("generating the CSR key: %v", err)
	}
	csrDER, err := x509.CreateCertificateRequest(rand.Reader, &x509.CertificateRequest{
		Subject: pkix.Name{CommonName: "test.lab.internal"},
	}, key)
	if err != nil {
		t.Fatalf("creating the CSR: %v", err)
	}
	csrPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE REQUEST", Bytes: csrDER})

	signed, err := pki.SignCSR(ctx, &pkiissuerv1.SignCSRRequest{CsrPem: string(csrPEM), TtlSeconds: 3600})
	if err != nil {
		t.Fatalf("SignCSR: %v", err)
	}
	if signed.GetPrivateKeyPem() != "" {
		t.Error("SignCSR: private_key_pem should stay empty, the key belongs to the caller")
	}
	signedLeaf := parseCertPEM(t, signed.GetCertPem())
	if signedLeaf.Subject.CommonName != "test.lab.internal" {
		t.Errorf("SignCSR: CN = %q, want test.lab.internal", signedLeaf.Subject.CommonName)
	}
	verifyAgainstRoot(t, signed.GetChainPem(), chain.GetChainPem())

	if _, err := pki.SignSSH(ctx, &pkiissuerv1.SignSSHRequest{KeyId: "test"}); err == nil {
		t.Error("SignSSH: unexpected success, should still be Unimplemented")
	}
}

// TestStepCAReusesRootAcrossRestarts proves the CA's idempotence
// (docs/03-module-contract.md §4 rule 3) across a real restart of the module
// (a new process, not just an in-memory cache): the second instance must find
// the SAME root, stored by the first one through core.secrets, and not
// generate a new one.
func TestStepCAReusesRootAcrossRestarts(t *testing.T) {
	rt := testutil.RequireRuntime(t)
	store := newTestSecretsStore(t)
	ctx := context.Background()

	first := launchStepCAWithStore(t, rt, store)
	firstChain, err := first.CAChain(ctx, &pkiissuerv1.Empty{})
	if err != nil {
		t.Fatalf("CAChain (first instance): %v", err)
	}

	second := launchStepCAWithStore(t, rt, store)
	secondChain, err := second.CAChain(ctx, &pkiissuerv1.Empty{})
	if err != nil {
		t.Fatalf("CAChain (second instance): %v", err)
	}

	if firstChain.GetChainPem() != secondChain.GetChainPem() {
		t.Error("the second step-ca instance regenerated a different chain instead of reusing the stored one")
	}
}

// TestStepCASignsThirdPartyIntermediate proves the exact scenario
// modules/vault (M7) needs: SignCSR with is_ca=true must produce a REAL
// intermediate, able to sign a leaf in turn, with a complete chain
// (third-party leaf -> third-party intermediate -> step-ca intermediate ->
// root) valid up to step-ca's root (docs/07-mvp-modules.md: "pki_int signed by
// the root"). This path revealed a real bug (insufficient pathlen on step-ca's
// default root), found while validating the Vault workflow by hand in Docker
// before writing modules/vault.
func TestStepCASignsThirdPartyIntermediate(t *testing.T) {
	pki := launchStepCA(t)
	ctx := context.Background()

	rootChain, err := pki.CAChain(ctx, &pkiissuerv1.Empty{})
	if err != nil {
		t.Fatalf("CAChain: %v", err)
	}

	// CSR of a third-party intermediate (as modules/vault would do for
	// pki_int/intermediate/generate/internal).
	intKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("generating the third-party intermediate's key: %v", err)
	}
	intCSRDER, err := x509.CreateCertificateRequest(rand.Reader, &x509.CertificateRequest{
		Subject: pkix.Name{CommonName: "Third Party Intermediate"},
	}, intKey)
	if err != nil {
		t.Fatalf("creating the third-party intermediate's CSR: %v", err)
	}
	intCSRPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE REQUEST", Bytes: intCSRDER})

	signedInt, err := pki.SignCSR(ctx, &pkiissuerv1.SignCSRRequest{
		CsrPem: string(intCSRPEM), IsCa: true, PathLenConstraint: 0, TtlSeconds: 3600,
	})
	if err != nil {
		t.Fatalf("SignCSR (is_ca=true): %v", err)
	}
	intCert := parseCertPEM(t, signedInt.GetCertPem())
	if !intCert.IsCA {
		t.Fatal("SignCSR (is_ca=true): the resulting certificate is not a CA")
	}
	verifyAgainstRoot(t, signedInt.GetChainPem(), rootChain.GetChainPem())

	// The third-party intermediate now signs its own leaf, in pure Go — this
	// proves the issued certificate is a REAL working intermediate, not just
	// marked CA:TRUE.
	leafKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("generating the leaf key: %v", err)
	}
	leafTemplate := &x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject:      pkix.Name{CommonName: "leaf-under-third-party.lab.internal"},
		NotBefore:    intCert.NotBefore,
		NotAfter:     intCert.NotAfter,
		KeyUsage:     x509.KeyUsageDigitalSignature,
	}
	leafDER, err := x509.CreateCertificate(rand.Reader, leafTemplate, intCert, &leafKey.PublicKey, intKey)
	if err != nil {
		t.Fatalf("signing the leaf with the third-party intermediate: %v", err)
	}
	leafPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: leafDER})

	fullChain := string(leafPEM) + signedInt.GetChainPem()
	verifyAgainstRoot(t, fullChain, rootChain.GetChainPem())
}
